### ISSUE TITLE
problem about  prepareOriginalMethods in FBAllocationTrackerImpl.mm

### ISSUE THREAD

**Issue by mitchell-dream** [facebook/FBAllocationTracker#20]
Why does FBAllocationTrackerImpl.mm must use prepareOriginalMethods method to replace method but not replace alloc and fb_newAlloc directly? @Gricha

**Comment by FinnChen** [comment]
+1

**Comment by gunnarku** [comment]
Because `prepareOriginalMethods()` is called from two different places (`void turnOnTracking(void)` and `void turnOffTracking(void)`) and having a separate method to do this work provides better decomposition, makes code more understandable, and avoids duplication.

Please open a new issue if there's something else here beside a general question about why code was structured in a certain way.
